name: Flutter Build iOS

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: macos-latest
    name: Build Flutter iOS App for Device Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Install Fastlane
        run: sudo gem install fastlane -N

      - name: Build iOS App (Release) with Flutter
        run: flutter build ios --release --no-codesign

      - name: Configure Fastlane Environment
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }} # 在 GitHub Secrets 中设置你的 Apple ID
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }} # 在 GitHub Secrets 中设置你的 Apple ID 密码或应用专用密码
        run: |
          cd ios
          fastlane gym \
            --scheme Runner \
            --export_method ad-hoc \ # 或者使用 'development' 根据你的 Provisioning Profile 类型选择
            --output_directory ../build/ios \
            --clean

      - name: Package artifact
        run: |
          cd build/ios
          zip -r Runner-app.zip Runner.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-ios-app-for-device-testing
          path: build/ios/Runner-app.zip
