name: Flutter Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    name: Build Flutter iOS App

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Setup CocoaPods
        run: |
          cd ios
          pod setup --verbose
          pod install --repo-update

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Install Fastlane
        run: sudo gem install fastlane -N
        
      - name: Build iOS App with Fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS: "-t DAV"
        run: |
          cd ios
          fastlane build_app \
            --scheme Runner \
            --configuration Release \
            --export_method ad-hoc \                    # 分发方式：ad-hoc / app-store / development
            --export_options ./export_options.plist \   # 导出配置文件
            --output_name Runner.ipa \
            --verbose

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-ios-app.ipa
          path: ios/Runner.ipa
          if: success()
