name: Flutter Build iOS

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: macos-latest
    name: Build Flutter iOS App

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Install Fastlane
        run: sudo gem install fastlane -N

      - name: Build iOS App (Release)
        run: flutter build ios --release --no-codesign

      - name: Archive and Export iOS App
        run: |
          cd ios
          fastlane snapshot init || true # 初始化（如果没用 fastlane）
          fastlane gym --scheme Runner --export_method development --output_directory ../build/ios --clean

      - name: Package artifact
        run: |
          cd build/ios
          zip -r Runner-app.zip Runner.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-ios-app
          path: build/ios/Runner-app.zip
