name: Flutter Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    name: Build Flutter iOS App

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Install CocoaPods dependencies
        run: cd ios && pod install --repo-update --verbose

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Install Fastlane
        run: sudo gem install fastlane -N

      - name: Build iOS App (Release) with Flutter
        run: flutter build ios --release --no-codesign

      - name: Configure Fastlane Environment
        env:
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          FASTLANE_USER: ${{secrets.FASTLANE_USER}}
          FASTLANE_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{secrets.MATCH_GIT_BASIC_AUTHORIZATION}}
        run: |
          cd ios
          fastlane build_app

      - name: Package artifact
        run: |
          cd build/ios
          zip -r Runner-app.zip Runner.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-ios-app-for-device-testing
          path: build/ios/Runner-app.zip
